<a href="https://colab.research.google.com/github/Rifat429/DL/blob/main/ANN_churn_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd

df= pd.read_csv("/content/Churn_Modelling.csv")
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [24]:
## removing unnecessary column
df.drop(columns = ['RowNumber','CustomerId','Surname'],inplace=True)

In [25]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [26]:
df['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [27]:
df['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [28]:
####One hot Encoding
df = pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)

In [29]:
X = df.drop(columns=['Exited'])
y = df['Exited'].values

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [30]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_trf = scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)

In [31]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [32]:
X_train_trf.shape

(8000, 11)

In [33]:
######## Defining ANN model

model = Sequential()
#### 3 is defining the perceptron numbers in the input layer..
#### input_dim 11 means that the 3 perceptron will receive 11 input and the activation function is sigmoid here.
model.add(Dense(3,activation='sigmoid',input_dim=11))
model.add(Dense(1,activation='sigmoid'))


In [34]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 3)                 36        
                                                                 
 dense_3 (Dense)             (None, 1)                 4         
                                                                 
Total params: 40 (160.00 Byte)
Trainable params: 40 (160.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [37]:
model.compile(loss="binary_crossentropy", optimizer="adam")

In [39]:
epochs=20
model.fit(X_train_trf,y_train,epochs=20)

Epoch 1/20
250/250 [==============================] - 1s 2ms/step - loss: 0.4933
Epoch 2/20
250/250 [==============================] - 1s 4ms/step - loss: 0.4742
Epoch 3/20
250/250 [==============================] - 1s 6ms/step - loss: 0.4621
Epoch 4/20
250/250 [==============================] - 1s 6ms/step - loss: 0.4533
Epoch 5/20
250/250 [==============================] - 1s 2ms/step - loss: 0.4465
Epoch 6/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4411
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4368
Epoch 8/20
250/250 [==============================] - 0s 1ms/step - loss: 0.4334
Epoch 9/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4308
Epoch 10/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4289
Epoch 11/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4276
Epoch 12/20
250/250 [==============================] - 0s 2ms/step - loss: 0.4264
Epoch 13/20
250/250 [====

In [43]:
## to see the wieights of the first layer
model.layers[0].get_weights()

[array([[-1.5640646e-01,  3.4032661e-01, -7.2023667e-02],
        [ 2.3029282e+00, -4.2409316e-01, -1.9223675e+00],
        [-1.4212523e-01,  1.7073436e-01,  4.4009272e-02],
        [-4.9344584e-02, -2.3830046e-01, -1.6235891e-01],
        [ 1.6637318e-01,  8.3758688e-01, -6.4278558e-02],
        [-2.0784438e-01,  1.6323693e-01, -1.2705547e-01],
        [ 4.9721904e-02,  1.3439925e+00,  2.2324362e-01],
        [ 2.3740192e-04,  8.0203600e-03, -7.2788544e-02],
        [ 3.1075850e-01, -5.0523579e-01, -5.8185548e-01],
        [-1.2623438e-01,  3.5102386e-02, -1.6200128e-01],
        [-1.3758299e-01,  3.8419515e-01,  4.7047797e-01]], dtype=float32),
 array([-0.15543735,  0.7477744 ,  0.1063602 ], dtype=float32)]

In [45]:
## to see the weights of the second layer
model.layers[1].get_weights()

[array([[ 0.62200534],
        [-1.3297513 ],
        [-2.035726  ]], dtype=float32),
 array([-0.04124714], dtype=float32)]

In [51]:
### we used sigmoid which gives us the result between 0 to 1. thats why we did not get our output as 0 and 1
model.predict(X_test)

63/63 [==============================] - 0s 2ms/step


array([[0.48968968],
       [0.48968968],
       [0.48968968],
       ...,
       [0.48968968],
       [0.48968968],
       [0.48968968]], dtype=float32)

In [52]:
### we will use a threshold method to convert the result into 0 and 1
import numpy as np
y_log = model.predict(X_test)
y_pred = np.where(y_log>0.5, 1, 0)

63/63 [==============================] - 0s 1ms/step


In [53]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7975

In [54]:


model = Sequential()
model.add(Dense(11,activation='relu',input_dim=11))
model.add(Dense(15, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [57]:
model.compile(loss="binary_crossentropy", optimizer="Adam",metrics="accuracy")

In [58]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 11)                132       
                                                                 
 dense_5 (Dense)             (None, 15)                180       
                                                                 
 dense_6 (Dense)             (None, 4)                 64        
                                                                 
 dense_7 (Dense)             (None, 1)                 5         
                                                                 
Total params: 381 (1.49 KB)
Trainable params: 381 (1.49 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [60]:
Epochs=200
model.fit(X_train_trf,y_train,epochs=Epochs,validation_split=0.2)

Epoch 1/200
200/200 [==============================] - 2s 10ms/step - loss: 0.3097 - accuracy: 0.8722 - val_loss: 0.3143 - val_accuracy: 0.8769
Epoch 2/200
200/200 [==============================] - 1s 5ms/step - loss: 0.3084 - accuracy: 0.8739 - val_loss: 0.3159 - val_accuracy: 0.8794
Epoch 3/200
200/200 [==============================] - 1s 5ms/step - loss: 0.3082 - accuracy: 0.8744 - val_loss: 0.3176 - val_accuracy: 0.8750
Epoch 4/200
200/200 [==============================] - 1s 4ms/step - loss: 0.3086 - accuracy: 0.8741 - val_loss: 0.3194 - val_accuracy: 0.8744
Epoch 5/200
200/200 [==============================] - 1s 4ms/step - loss: 0.3093 - accuracy: 0.8716 - val_loss: 0.3203 - val_accuracy: 0.8756
Epoch 6/200
200/200 [==============================] - 1s 4ms/step - loss: 0.3073 - accuracy: 0.8756 - val_loss: 0.3247 - val_accuracy: 0.8712
Epoch 7/200
200/200 [==============================] - 1s 4ms/step - loss: 0.3073 - accuracy: 0.8747 - val_loss: 0.3235 - val_accuracy: 0.876

In [61]:
model.predict(X_test)

63/63 [==============================] - 0s 1ms/step


array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [1.],
       [1.]], dtype=float32)

In [68]:
### we will use a threshold method to convert the result into 0 and 1
import numpy as np
y_log = model.predict(X_test_trf)
y_pred = np.where(y_log>0.5, 1, 0)

63/63 [==============================] - 0s 2ms/step


In [69]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8545