<a href="https://colab.research.google.com/github/Rifat429/DL/blob/main/backprpagation_with_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [5]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [6]:
model= Sequential()
model.add(Dense(2,activation="linear",input_dim=2))
model.add(Dense(1,activation="linear"))

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [8]:
model.get_weights()

[array([[-0.21522379,  0.98325956],
        [ 0.16377747, -1.0298702 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.3353868],
        [ 1.3971137]], dtype=float32),
 array([0.], dtype=float32)]

In [16]:
######## we can create our custom weights and define them and override the existing weights as per our desire
new_weights=[np.array([[0.1,  0.1],
        [ 0.1, 0.1 ]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1],
        [ 0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]


In [17]:
model.set_weights(new_weights)

In [18]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [19]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss="mean_squared_error",optimizer=optimizer)

In [21]:
model.fit(df.iloc[:,0:-1].values,df["lpa"].values,epochs=75,batch_size=1)

Epoch 1/75
4/4 [==============================] - 0s 3ms/step - loss: 19.9251
Epoch 2/75
4/4 [==============================] - 0s 3ms/step - loss: 19.3445
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 18.8420
Epoch 4/75
4/4 [==============================] - 0s 3ms/step - loss: 18.3010
Epoch 5/75
4/4 [==============================] - 0s 3ms/step - loss: 17.8023
Epoch 6/75
4/4 [==============================] - 0s 3ms/step - loss: 17.2095
Epoch 7/75
4/4 [==============================] - 0s 3ms/step - loss: 16.7005
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 16.1561
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 15.6784
Epoch 10/75
4/4 [==============================] - 0s 3ms/step - loss: 15.0655
Epoch 11/75
4/4 [==============================] - 0s 3ms/step - loss: 14.5698
Epoch 12/75
4/4 [==============================] - 0s 3ms/step - loss: 14.0086
Epoch 13/75
4/4 [==============================] - 0s 3ms/ste