<a href="https://colab.research.google.com/github/Rifat429/DL/blob/main/Embedding(Sentiment_analysis_Simple_RNN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

docs = ['Hello Bangladesh',
		'Bangladesh Bangladesh',
		'hurray hurray hurray',
		'win or loss bangladesh is the best',
		'Harleo bangladesh jitleo bangladesh',
		'shakib shakib',
		'khela pare na',
		'seikh hasina is the killer hasina',
		'stepdown hasina',
		'Dictator Hasina']

In [3]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [4]:
tokenizer.fit_on_texts(docs)

In [5]:
len(tokenizer.word_index) ##unique words

20

In [6]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[7, 1],
 [1, 1],
 [3, 3, 3],
 [8, 9, 10, 1, 4, 5, 11],
 [12, 1, 13, 1],
 [6, 6],
 [14, 15, 16],
 [17, 2, 4, 5, 18, 2],
 [19, 2],
 [20, 2]]

In [7]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 7,  1,  0,  0,  0,  0,  0],
       [ 1,  1,  0,  0,  0,  0,  0],
       [ 3,  3,  3,  0,  0,  0,  0],
       [ 8,  9, 10,  1,  4,  5, 11],
       [12,  1, 13,  1,  0,  0,  0],
       [ 6,  6,  0,  0,  0,  0,  0],
       [14, 15, 16,  0,  0,  0,  0],
       [17,  2,  4,  5, 18,  2,  0],
       [19,  2,  0,  0,  0,  0,  0],
       [20,  2,  0,  0,  0,  0,  0]], dtype=int32)

In [11]:
sequences.shape

(10, 7)

In [9]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [22]:
model = Sequential()
model.add(Embedding(input_dim=21, output_dim=2, input_length=7)) ##input dim = unique words +1 ..input_length = features of every sentences

model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.compile('adam','accuracy')

In [24]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step
[[[-0.01952145  0.0152972 ]
  [ 0.01930672 -0.04015265]
  [-0.032414   -0.04962734]
  [-0.032414   -0.04962734]
  [-0.032414   -0.04962734]
  [-0.032414   -0.04962734]
  [-0.032414   -0.04962734]]

 [[ 0.01930672 -0.04015265]
  [ 0.01930672 -0.04015265]
  [-0.032414   -0.04962734]
  [-0.032414   -0.04962734]
  [-0.032414   -0.04962734]
  [-0.032414   -0.04962734]
  [-0.032414   -0.04962734]]

 [[-0.00448314  0.02693884]
  [-0.00448314  0.02693884]
  [-0.00448314  0.02693884]
  [-0.032414   -0.04962734]
  [-0.032414   -0.04962734]
  [-0.032414   -0.04962734]
  [-0.032414   -0.04962734]]

 [[ 0.03314793  0.0418556 ]
  [-0.02062777 -0.04926404]
  [-0.01969935 -0.04130886]
  [ 0.01930672 -0.04015265]
  [ 0.03935765  0.02200511]
  [-0.01429371  0.01720539]
  [ 0.04231436  0.03065277]]

 [[ 0.02075671  0.04695499]
  [ 0.01930672 -0.04015265]
  [ 0.00250018 -0.04603153]
  [ 0.01930672 -0.04015265]
  [-0.032414   -0.04962734]
  [-0.032414   -0.04962734]
 

#applying on IMBD dataset

In [47]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [34]:
# unique_values, counts = np.unique(X_train, return_counts=True)
# print("Unique values:", unique_values)
# print("Counts:", counts)

In [48]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [49]:
X_train.shape

(25000, 50)

In [50]:
X_train[0].shape

(50,)

**we set the unique word limits to 10,000 ..2 is the output dimension..50 is the word size in every sentences**

In [53]:
model = Sequential()
model.add(Embedding(input_dim=100000, output_dim=2, input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_14"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_11 (Embedding)             │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_3 (SimpleRNN)             │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [54]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 17s 19ms/step - acc: 0.5556 - loss: 0.6678 - val_acc: 0.7799 - val_loss: 0.4646
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 18ms/step - acc: 0.8344 - loss: 0.3783 - val_acc: 0.8054 - val_loss: 0.4254
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 18ms/step - acc: 0.9072 - loss: 0.2458 - val_acc: 0.8021 - val_loss: 0.4727
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 19ms/step - acc: 0.9343 - loss: 0.1826 - val_acc: 0.7946 - val_loss: 0.5031
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 19ms/step - acc: 0.9570 - loss: 0.1282 - val_acc: 0.7892 - val_loss: 0.5697
